apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubernetes-instrumentor
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubernetesInstrumentor
subjects:
  - kind: ServiceAccount
    name: {{ .Values.kubernetesInstrumentor.serviceAccount }}
    namespace: {{ .Release.Namespace }}