apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.easyConnectServer.service.name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: easy-connect-server
  ports:
  - name: ui-server
    port: {{ .Values.easyConnectServer.service.port }}
    targetPort: {{ .Values.easyConnectServer.service.targetPort }}
  - name: http
    port: 80
    targetPort: 8080