apiVersion: apps/v1
kind: Deployment
metadata:
  name: easy-connect-ui
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: easy-connect-ui
  template:
    metadata:
      labels:
        app: easy-connect-ui
      annotations:
        logz.io/skip: "true"
    spec:
      containers:
        - name: easy-connect-ui
          image: "{{ .Values.easyConnectUi.image.repository }}:{{ .Values.easyConnectUi.image.tag }}"
          ports:
            - containerPort: {{ .Values.easyConnectUi.ports.http }}
          env:
            - name: EASY_CONNECT_SERVER_URL
              value: "{{ .Values.easyConnectServer.service.name }}"