apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-instrumentor
  namespace: {{ .Release.Namespace }}
  labels:
    app: kubernetes-instrumentor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubernetes-instrumentor
  template:
    metadata:
      labels:
        app: kubernetes-instrumentor
      annotations:
        logz.io/skip: "true"
    spec:
      serviceAccountName: {{ .Values.kubernetesInstrumentor.serviceAccount }}
      containers:
        - name: manager
          image: "{{ .Values.kubernetesInstrumentor.image.repository }}:{{ .Values.kubernetesInstrumentor.image.tag }}"
          resources:
            {{- toYaml .Values.kubernetesInstrumentor.resources | nindent 12 }}
          env:
            - name: MONITORING_SERVICE_ENDPOINT
              value: "{{ .Values.kubernetesInstrumentor.env.monitoringServiceEndpoint }}"
            - name: DOTNET_AGENT_IMAGE
              value: "{{ .Values.kubernetesInstrumentor.dotnetAgentImage.repository }}:{{ .Values.kubernetesInstrumentor.dotnetAgentImage.tag }}"
            - name: PYTHON_AGENT_IMAGE
              value: "{{ .Values.kubernetesInstrumentor.pythonAgentImage.repository }}:{{ .Values.kubernetesInstrumentor.pythonAgentImage.tag }}"
            - name: NODEJS_AGENT_IMAGE
              value: "{{ .Values.kubernetesInstrumentor.nodejsAgentImage.repository }}:{{ .Values.kubernetesInstrumentor.nodejsAgentImage.tag }}"
            - name: JAVA_AGENT_IMAGE
              value: "{{ .Values.kubernetesInstrumentor.javaAgentImage.repository }}:{{ .Values.kubernetesInstrumentor.javaAgentImage.tag }}"
          ports:
            - name: metrics-port
              containerPort: {{ .Values.kubernetesInstrumentor.ports.metricsPort }}
            - name: health-probe
              containerPort: {{ .Values.kubernetesInstrumentor.ports.healthProbePort }}
          args:
            - "--health-probe-bind-address=:{{ .Values.kubernetesInstrumentor.ports.healthProbePort }}"
            - "--metrics-bind-address=127.0.0.1:{{ .Values.kubernetesInstrumentor.ports.metricsPort }}"
            - "--leader-elect"
            - "--instrumentation-detector-tag={{ .Values.kubernetesInstrumentor.instrumentationDetectorImage.tag }}"
            - "--instrumentation-detector-image={{ .Values.kubernetesInstrumentor.instrumentationDetectorImage.repository }}"
        - name: kube-rbac-proxy
          image: gcr.io/kubebuilder/kube-rbac-proxy:v0.11.0
          args:
            - "--secure-listen-address=0.0.0.0:8443"
            - "--upstream=http://127.0.0.1:{{ .Values.kubernetesInstrumentor.ports.metricsPort }}/"
            - "--logtostderr=true"
            - "--v=0"
