apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.kubernetesInstrumentor.service.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: kubernetes-instrumentor
spec:
  ports:
    - name: http
      port: {{ .Values.kubernetesInstrumentor.service.port }}
      targetPort: {{ .Values.kubernetesInstrumentor.service.targetPort }}
  selector:
    app: kubernetes-instrumentor
