apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kubernetesInstrumentorLeaderElection
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: logzioLeaderElectionRole
subjects: 
  - kind: ServiceAccount
    name: {{ .Values.kubernetesInstrumentor.serviceAccount }}
    namespace: {{ .Release.Namespace }}