apiVersion: v2
name: logzio-monitoring
description: logzio-monitoring allows you to ship logs, metrics, traces and security reports from your Kubernetes cluster using the OpenTelemetry collector for metrics and traces, Fluentd for logs, and Trivy for security reports.
type: application
version: 0.5.6

sources:
  - https://github.com/logzio/logzio-helm
dependencies:
  - name: logzio-fluentd
    version: "0.20.2"
    repository: "file://../fluentd/"
    condition: logs.enabled
  - name: logzio-k8s-telemetry
    version: "0.0.28"
    repository: "file://../logzio-telemetry"
    condition: metricsOrTraces.enabled
  - name: logzio-trivy
    version: "0.2.1"
    repository: "file://../logzio-trivy"
    condition: securityReport.enabled
  - name: opencost
    version: "1.3.0"
    repository: "https://opencost.github.io/opencost-helm-chart"
    condition: finops.enabled

maintainers:
- name: tamirmich
  email: tamir.michaeli@logz.io
- name: yotamloe
  email: yotam.loewenbach@logz.io
- name: miriig
  email: miri.ignatiev@logz.io
